name: Sync Main-Master
on:
  push: { branches: main }
  workflow_dispatch:

# One-time commands for users to switch-over:
# ```sh
# git branch -m master main; git fetch origin; git branch -u origin/main main; git remote set-head origin -a
# ```

jobs:
  sync:
    uses: nodenv/.github/.github/workflows/sync-main-master.yml@v2
