name: Tag Major Version
on:
  push: { tags: "v*.*.*" }
  workflow_dispatch:

permissions: { contents: read }

jobs:
  tag:
    permissions: { contents: write }
    uses: nodenv/.github/.github/workflows/tag-major.yml@main
